name: My Blog
author: GongYunlong
url: https://g2431345491.github.io/
baseurl: 
resume_site: https://g2431345491.github.io/
description: 巩云龙的Github个人主页
github_username: g2431345491
github: https://github.com/g2431345491
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 1f62179a048bce139f59
    clientSecret : 1fff5332d205d0bffb0dbd7df0b0dd9e6c1411c1
    repo : g2431345491.github.io
    owner : g2431345491
    admin : g2431345491
    proxy: https://shielded-brushlands-08810.herokuapp.com/https://github.com/login/oauth/access_token

theme: jekyll-theme-cayman
